
export const en = {
  header_info_p:
    "Restaurateur? Join the Taster Platform and rapidly launch one of our iconic virtual restaurant brands from your existing kitchen!",
  header_info_btn1: "BECOME A PARTNER",
  header_info_btn2: "LEARN MORE",
  main_p: "The best of street food at home",
  main_p2:
    "Taster is a collection of online restaurants dedicated to bringing the best of street food to you.",
  main_div_p: "Discover our brands",
  Bitesize_Stats: "Bitesize Stats",
  ul_2_li: "4 Years",
  ul_2_li2: "425,364 Cheese Slices",
  ul_2_li3: "9.2 million Sweet Potato Fries",
  pre_footer_ul1: "7104 km of noodles",
  pre_footer_ul2: "314,530 tiger prawns",
  pre_footer_ul3: "1,000,000+ attractions",
  pre_footer_ul_1: "100 restaurants",
  pre_footer_ul_2: "25 Cities",
  pre_footer_ul_3: "5 brands",
  pre_footer_ul_4: "And more!",
  footer_ul1_li1: "Our restaurants",
  footer_ul1_li2: "B Yang Dang",
  footer_ul1_li3: "Burgers",
  footer_ul1_li4: "Mission Saigon",
  footer_ul1_li5: "Fry came out",
  footer_ul1_li6: "Stacksando",
   Find_us: "find us",
  Address: "Address",
  Sorry: "Sorry, we're just a digital food court",
  Order: "Order at",
  Android: "Download on Android",
  iOS: "Download on iOS",
  Corporate: "Business",
  Contact: "contact",
  Our_Story: "Our history",
  Jobs: "Vacant jobs",
  Support: "Support",
  Socials: "Social",
  Instagram: "Instagram",
Facebook: "Facebook",
};
