// export const ua = {
//   title: "Якісне навчання IT-спеціальностям для дорослих та дітей у Вінниці",
//   main_text:
//     "Якщо у вас є питання про курси або ви не знаєте, що вибрати, залиште свій номер, ми зателефонуємо та детально проконсультуємо.",
//   head_desc: "Чому наші IT-курси найкращі?",
//   description:
//     "Академія ITSTEP працює з 1999 року, коли сфера IT лише починала розвиватися та набувати популярності. Вже тоді ми випускали перших програмістів, веб-дизайнерів та інших IT-фахівців. Сьогодні ми надаємо учням навички, яких потребують роботодавці та сучасний бізнес — жодної сухої теорії та «води». Роботодавцям не потрібні ваші знання — їм потрібна компетенція у вирішенні робочих завдань та налаштування бізнес-процесів. Академія ITSTEP — це комфортне середовище, в якому викладачі та студенти працюють у синергії для досягнення результату.",
// };
export const fr = {
  header_info_p:
    "Restaurateur? Rejoignez la plateforme Taster et lancez rapidement l'une de nos marques de restaurants virtuels emblématiques depuis votre cuisine existante !",
  header_info_btn1: "PARITER À UN PARTENAIRE",
  header_info_btn2: "MER DE LARN",
  main_p: "Le meilleur de la street food à la maison",
  main_p2:
    "Taster est une collection de restaurants en ligne dédiés à apporter le meilleur de la cuisine de rue à IU.",
  main_div_p: "Découvrez nos marques",
  Bitesize_Stats: "Statistiques sur la taille des bouchées",
  ul_2_li: "h Années",
  ul_2_li2: "425.364 Tranches de fromage",
  ul_2_li3: "i,2 millions Le monde de la pomme de terre frites",
   pre_footer_ul1: "7104 km de nouilles",
  pre_footer_ul2: "314 530 crevettes tigrées",
  pre_footer_ul3: "Plus de 1 000 000 d'attractions",
  pre_footer_ul_1: "100 restaurants",
  pre_footer_ul_2: "25 Tsite",
  pre_footer_ul_3: "5 marques",
  pre_footer_ul_4: "Mer des Andes!",
  footer_ul1_li1: "Vos restaurants",
  footer_ul1_li2: "B Young Dang",
  footer_ul1_li3: "Des hamburgers",
  footer_ul1_li4: "Mission Saïgon",
  footer_ul1_li5: "Fry est sorti",
  footer_ul1_li6: "Stacksando",
  Find_us: "trouve nous",
  Address: "Adresse",
  Sorry: "Désolé, nous ne sommes qu'une aire de restauration numérique",
  Order: "Commandez à",
  Android: "Télécharger sur Android",
  iOS: "Télécharger sur iOS",
  Corporate: "Entreprise",
  Contact: "contact",
  Our_Story: "Notre histoire",
  Jobs: "Postes vacants",
  Support: "Soutien",
  Socials: "Sociale",
  Instagram: "Instagram",
Facebook: "Facebook",
};
