export const ua = {
  header_info_p:
    "Ресторатор? Приєднуйтесь до платформи Taster і швидко запустіть один із наших культових брендів віртуальних ресторанів із вашої наявної кухні!",
  
  header_info_btn1: "СТАТИ ПАРТНЕРОМ",
  header_info_btn2: "Вивчайте більше",
  main_p: "Найкраще з вулиці харчування вдома",
  main_p2:
    "Taster — це колекція онлайн-ресторанів, які пропонують вам найкращу вуличну їжу.",
  main_div_p: "Відкрийте для себе наші бренди",
  Bitesize_Stats: "Bitesize Статистика",
  ul_2_li: "4 роки",
  ul_2_li2: "425,364  Скибочки сиру",
  ul_2_li3: "9.2 мільйонів Солодка картопля Картопля фрі",
  pre_footer_ul1: "7104 км локшини",
  pre_footer_ul2: "314,530 тигрові креветки",
  pre_footer_ul3: "1 000 000+ атракціони",
  pre_footer_ul_1: "100 ресторанів",
  pre_footer_ul_2: "25 Міст",
  pre_footer_ul_3: "5 брендів",
  pre_footer_ul_4: "І більше!",
  footer_ul1_li1: "Наші ресторани",
  footer_ul1_li2: "Б Ян Данг",
  footer_ul1_li3: "Бургери",
  footer_ul1_li4: "Місія Сайгон",
  footer_ul1_li5: "Вийшов Фрай",
  footer_ul1_li6: "Stacksando",
  Find_us: "Знайди нас",
  Address: "Адреса",
  Sorry: "Вибачте, ми просто цифровий фудкорт",
  Order: "Замовити на",
  Android: "Завантажити на Android",
  iOS: "Завантажити на iOS",
  Corporate: "Корпоративний",
  Contact: "контакт",
  Our_Story: "Наша історія",
  Jobs: "Вакансії",
  Support: "Підтримка",
  Socials: "Соціальні",
  Instagram: "Instagram",
Facebook: "Facebook",

};
